### ISSUE TITLE
Tectonic + Biber

### ISSUE THREAD

**Issue by malramsay64** [PHPirates/travis-ci-latex-pdf#10]
I have a [solution](https://github.com/malramsay64/phd-thesis/blob/master/.travis.yml) for using biber with tectonic. Do you think it would it be a worthwhile addition or just add too much noise?

**Comment by PHPirates** [comment]
Oh that's nice! It would definitely be very useful to add. I haven't taken the time myself to figure out how to use biber+biblatex package, part of the reason being that my LaTeX editor (TeXiFy) may not work well with it. 

Actually the [tinytex .travis.yml](https://github.com/PHPirates/travis-ci-latex-pdf/blob/master/3-tinytex/.travis.yml) in this repo seems to assume biber :) 

I guess it should be added as note in the readme, and probably a `.travis.yml` file which is verified to work in 1b-tectonic-miniconda folder. If you want you can create a PR, otherwise I'll do so myself later on. Many thanks for letting me know!

PS Can I ask how you actually got to using Travis to build your phd, and how you got to switching to Tectonic? I'm very curious!

[edit] I just found your [blog post](https://malramsay.com/post/compiling_latex_on_travis/) which is definitely the best post about latex+ci that I have seen so far, I will definitely link to it.

[edit2] Funny I see you mention language: generic (and language: minimal) since I recently learned that from an example Haskell .travis.yml...

**Comment by malramsay64** [comment]
I will put something together over the weekend. 

Thanks!!! I'm pretty sure I first found out about tectonic from your stackoverflow [post](https://tex.stackexchange.com/questions/398830/how-to-build-my-latex-automatically-using-travis-ci), and since it is installable using conda I think it's great.
