### ISSUE TITLE
Fails to deploy, but still in assets

### ISSUE THREAD

**Issue by Pankratius** [PHPirates/travis-ci-latex-pdf#17]
I tried using your code (Method 1a), and I can find the compiled .pdf-file in the assets-branch of my repo. However, I still get the warning that travis failed to deploy, and don't find the file in the repo.

**Comment by PHPirates** [comment]
Thank you very much for trying it out and for reporting! That method was updated just a few days ago, so maybe I missed some instructions - all feedback is very welcome.

I'm assuming this is your setup: https://github.com/Pankratius/travistest and I found the errored build here: https://travis-ci.org/Pankratius/travistest/builds/441098185
The actual error in the build is
```
GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
```
Might it be you are using the GitHub API v3 with OAuth instead of the GitHub apps API? Are you sure you executed the first two steps of the [instructions](https://github.com/PHPirates/travis-ci-latex-pdf#instructions-for-building-with-docker-and-tectonic) and installed the Travis GitHub App, making sure the repository in question is enabled?


By the way, for some reason I do see the pdfs uploaded at your releases https://github.com/Pankratius/travistest/releases even though the deploy failed, did you upload them yourself manually? I'm also not sure what you mean with assets-branch?

**Comment by Pankratius** [comment]
Yes, you are right about my setup.
I don't know where I would check if I am using GitHub API v3 with OAuth or GitHub apps API.
But I did not put the .pdf in the releases (thats exactly what I meant with the assets-branch).

**Comment by PHPirates** [comment]
But did you follow the instructions I linked to? They say:

> Now you should be in Personal settings | Applications | Travis CI | Configure and you can allow access to repositories, either select repos or all repos.

If you go there, do you have 'all repositories' selected, or the one you are trying to build?

**Comment by Pankratius** [comment]
I think I installed everything correctly, but I am not sure if I am using the GitHub API v3 with OAuth or GitHub apps API, nor where I would check that...
And I did not put the .pdf in my releases, I don't know how they ended up there (that is also what I mean by the assets-branch.)

**Comment by PHPirates** [comment]
Yes yes I understand that you're not sure about the API, I don't really know myself :smile: but can you confirm that you see 'all repositories' button selected in your Settings | Applications | Travis CI | Configure?

I understand that you did not put the .pdf in your releases, that's why I'm asking the question above, to check if the Travis App (which uses the Apps API I think instead of the OAuth API) is installed correctly :) 

[Edit] Actually, in settings in the tab 'Authorized OAuth Apps' you can see all the apps which you use with OAuth API. Travis should not be there. Can you confirm that?

**Comment by WtfJoke** [comment]
I would also try to use https://github.com/travis-ci/travis.rb#installation and then execute `travis setup releases` in your repo and then replace the api-key in .travis.yml (when you havent done this already). Maybe your key was generated with wrong credentials?

**Comment by PHPirates** [comment]
Good point, I forgot you had to do that - but my very own instructions [here in the readme](https://github.com/PHPirates/travis-ci-latex-pdf#to-automatically-deploy-pdfs-to-github-release) indicate that the Travis gem (at least at that time) uses OAuth :smile:
